name: Detect Secrets

on:
  pull_request:
    branches:
      - main  # Triggers on PRs targeting the main branch
  push:
    branches:
      - main  # Triggers on pushes to the main branch

jobs:
  detect-secrets:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade "git+https://github.com/ibm/detect-secrets.git@master#egg=detect-secrets"

      - name: Validate .secrets.baseline JSON
        run: |
          if ! jq empty .secrets.baseline; then
            echo ".secrets.baseline is not valid JSON!"
            exit 1
          else
            echo ".secrets.baseline is valid JSON."
          fi

      - name: Run detect-secrets audit
        id: audit
        run: |
          output=$(detect-secrets audit --report --fail-on-unaudited --fail-on-live --fail-on-audited-real .secrets.baseline 2>&1) || true

      - name: Check audit results
        run: |
          if echo "$output" | grep -q "All checks have passed"
            echo "All checks have passed."
          else
            echo "$output"
            exit 1
          fi
